events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;
    upstream openwebui_backend {
        server openwebui:8080;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://openwebui_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
        }


        location /health {
            return 200 "Frontend OK";
            add_header Content-Type text/plain;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
            proxy_connect_timeout 60;
        }

        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
            proxy_connect_timeout 60;
        }

        location /node-exporter/ {
            proxy_pass http://node-exporter:9100/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering off;
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
            proxy_connect_timeout 60;
        }
    }
}