events {
    worker_connections 1024;
}

http {
    # Группа наших серверов vLLM (2 локальных + 2 на втором компе)
    upstream vllm_cluster {
        # Реплики на текущем компе (Комп 1). 
        # Nginx видит их по именам контейнеров в сети Docker
        server vllm-local-1:8000;
        server vllm-local-2:8000;


        # server 192.168.1.100:8001; 
        # server 192.168.1.100:8002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://vllm_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 3600;
        }
    }
}